# Generated by Django 5.0 on 2023-12-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.CharField(max_length=4),
        ),
    ]
