# Generated by Django 5.0.1 on 2024-08-24 10:00

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="order",
        ),
        migrations.RemoveField(
            model_name="education",
            name="order",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="order",
        ),
        migrations.AddField(
            model_name="competition",
            name="_order",
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="education",
            name="_order",
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="_order",
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name="competition",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("_order",),
                name="_order_unique_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="education",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("_order",),
                name="_order_unique_education",
            ),
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("_order",),
                name="_order_unique_expeerience",
            ),
        ),
    ]
