# Generated by Django 5.0 on 2023-12-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "minigrim0",
            "0002_alter_education_end_date_alter_education_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
