# Generated by Django 5.0.1 on 2024-01-24 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0002_remove_repository_id_alter_repository_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Repository",
        ),
    ]
