# Generated by Django 5.0.1 on 2024-08-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0002_remove_competition_order_remove_education_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="_order",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="education",
            name="_order",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="experience",
            name="_order",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
