# Generated by Django 5.0 on 2024-01-06 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0003_alter_competition_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
