# Generated by Django 5.0.1 on 2024-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0003_alter_competition__order_alter_education__order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="place",
            field=models.CharField(help_text="Markdown is supported", max_length=255),
        ),
        migrations.AlterField(
            model_name="experience",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="name",
            field=models.CharField(max_length=100, verbose_name="experience_name"),
        ),
    ]
