# Generated by Django 5.0 on 2024-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0004_alter_skill_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="level",
            field=models.CharField(
                choices=[
                    ("beg", "Beginner"),
                    ("int", "Intermediate"),
                    ("flu", "fluent"),
                    ("nat", "native"),
                ],
                max_length=100,
            ),
        ),
    ]
