# Generated by Django 5.0.1 on 2024-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigrim0", "0004_alter_education_place_alter_experience_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="details",
            field=models.TextField(
                blank=True, help_text="Markdown is supported", null=True
            ),
        ),
    ]
