# Generated by Django 5.1.1 on 2025-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigrim0', '0005_alter_skill_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image for CV (recommended: square format, 200x200px)', null=True, upload_to='cv_images/')),
                ('name', models.CharField(default='Florent Grimau', max_length=100)),
                ('title', models.CharField(default='Master Student in Embedded Systems', max_length=200)),
                ('address', models.CharField(default='Stockholm - Sweden', max_length=200)),
                ('email', models.EmailField(default='grimauflorent@gmail.com', max_length=254)),
                ('github_username', models.CharField(default='Minigrim0', max_length=100)),
                ('birth_date', models.CharField(default='22 Sept 2000', max_length=20)),
            ],
            options={
                'verbose_name': 'CV Profile',
                'verbose_name_plural': 'CV Profile',
            },
        ),
    ]
