# Generated by Django 5.1.1 on 2025-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minigrim0", "0006_cvprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvprofile",
            name="professional_summary",
            field=models.TextField(
                default="Passionate about embedded systems and low-level programming. Experienced in C, C++, Python, and Rust. Skilled in microcontroller programming, real-time operating systems, and hardware interfacing. Strong problem-solving abilities and a collaborative team player.",
                help_text="Markdown is supported",
            ),
        ),
    ]
