# Generated by Django 5.1.1 on 2025-09-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minigrim0", "0008_skillcategory_skill_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.CreateModel(
            name="SkillSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("_order", models.IntegerField(default=0, editable=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="minigrim0.skillcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="minigrim0.skillsubcategory",
            ),
        ),
    ]
