# Generated by Django 5.1.1 on 2025-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minigrim0", "0009_remove_skill_level_skillsubcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillcategory",
            name="_order",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
