services:
  web:
    image: minigrim0-web:latest
    build:
      dockerfile: docker/web.dockerfile
      context: ..
    environment:
      - DEBUG=False
      - LOGLEVEL=INFO
      - REDIS_URL=redis://redis:6379
    secrets:
      - SECRET_KEY
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - ALLOWED_HOSTS
      - PLAUSIBLE_URL
      - PLAUSIBLE_DOMAIN
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - redis
      - postgres
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.githubcron.schedule: "@every 1d"
      ofelia.job-exec.githubcron.command: "/bin/minigrim0 >> minigrim0.log && python manage.py fetchrepositories >> repo.log"
      ofelia.job-exec.githubcron.timezone: "Europe/Stockholm"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - private

  nginx:
    image: minigrim0-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/srv/static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minigrim0-web.entrypoints=https"
      - "traefik.http.routers.minigrim0-web.rule=Host(`minigrim0.xyz`)"
      - "traefik.http.routers.minigrim0-web.service=nginx-minigrim0-web"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - web
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - traefik-proxy
      - private

  postgres:
    image: postgres:15
    secrets:
      - DB_USER
      - DB_NAME
      - DB_PASSWORD
    environment:
      - POSTGRES_USER_FILE=/run/secrets/DB_USER
      - POSTGRES_DB_FILE=/run/secrets/DB_NAME
      - POSTGRES_PASSWORD_FILE=/run/secrets/DB_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - private

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - private

  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - web
    networks:
      - private

  plausible_db:
    image: postgres:15
    volumes:
      - plausible_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=plausible
      - POSTGRES_PASSWORD=plausible
      - POSTGRES_DB=plausible_db
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - private

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    volumes:
      - plausible_events_data:/var/lib/clickhouse
      - ./plausible/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./plausible/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - private

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    secrets:
      - SECRET_KEY_BASE
      - TOTP_VAULT_KEY
    environment:
      - BASE_URL=https://analytics.minigrim0.xyz
      - DATABASE_URL=postgres://plausible:plausible@plausible_db:5432/plausible_db
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.entrypoints=https"
      - "traefik.http.routers.plausible.rule=Host(`analytics.minigrim0.xyz`)"
      - "traefik.http.routers.plausible.service=plausible-service"
      - "traefik.http.services.plausible-service.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-proxy"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - traefik-proxy
      - private

volumes:
  static_volume:
  postgres_data:
  redis_data:
  plausible_db_data:
  plausible_events_data:

networks:
  traefik-proxy:
    external: true
  private:
    driver: overlay
    attachable: true

secrets:
  SECRET_KEY:
    file: secrets/secret_key.txt
  DB_USER:
    file: secrets/db_user.txt
  DB_PASSWORD:
    file: secrets/db_password.txt
  DB_HOST:
    file: secrets/db_host.txt
  DB_NAME:
    file: secrets/db_name.txt
  ALLOWED_HOSTS:
    file: secrets/allowed_hosts.txt
  PLAUSIBLE_URL:
    file: secrets/plausible_url.txt
  PLAUSIBLE_DOMAIN:
    file: secrets/plausible_domain.txt
  SECRET_KEY_BASE:
    file: secrets/plausible_secret_key_base.txt
  TOTP_VAULT_KEY:
    file: secrets/plausible_totp_vault_key.txt
