services:
  web:
    build:
      context: ..
      dockerfile: docker/web.dev.dockerfile
    volumes:
      - ..:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=minidebug
      - POSTGRES_PASSWORD=minidebug
      - POSTGRES_DB=minidebug_db

volumes:
  postgres_data:
