# Generated by Django 5.0.1 on 2024-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("name", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=256)),
                ("readme", models.TextField()),
                ("homepage", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "url",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("stars", models.IntegerField()),
            ],
        ),
    ]
