# Generated by Django 5.0.1 on 2024-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="readme",
            field=models.TextField(blank=True, null=True),
        ),
    ]
